name: 'Snorkell DocGen Client'
description: 'Use this GitHub Action to create documentation PR of your recent main branch merge.'
author: 'snorkell.ai'

inputs:
  client_id:
    description: 'Client ID for Snorkell'
    required: true
  api_key:
    description: 'API Key for Snorkell'
    required: true

outputs: {}

runs:
  using: 'composite'

  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Download Script
      run: |
        curl -o src/index.py https://raw.githubusercontent.com/SingularityX-ai/snorkell-documentation-client/v0.1.15-alpha/src/index.py
      shell: bash

    - name: Prepare Commit Message
      id: prep
      shell: bash
      run: |
        ESCAPED_COMMIT_MSG=$(printf '%s\n' "${{ github.event.head_commit.message }}" | jq -R -s -c .)
        echo "::set-output name=escaped_commit_msg::$ESCAPED_COMMIT_MSG"

    - name: Run Script
      shell: bash
      env:
        SNORKELL_CLIENT_ID: ${{ inputs.client_id }}
        SNORKELL_API_KEY: ${{ inputs.api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BRANCH_NAME: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        COMMIT_MSG: ${{ steps.prep.outputs.escaped_commit_msg }}

      run: |
        python src/index.py
         
branding:
  icon: 'upload-cloud'
  color: 'blue'
